opifer_rulesengine_rulesengine_condition:
    path: /rulesengine/condition/{provider}
    defaults: { _controller: OpiferRulesEngineBundle:RulesEngine:condition }
    methods: [GET]
    options:
        expose: true
