parameters:
    opifer.rulesengine.doctrine_provider.class: Opifer\RulesEngineBundle\Provider\DoctrineProvider
    opifer.rulesengine.form.condition_type.class: Opifer\RulesEngineBundle\Form\Type\ConditionType
    opifer.rulesengine.form.rulesengine_type.class: Opifer\RulesEngineBundle\Form\Type\RulesEngineType
    opifer.rulesengine.provider.pool.class: Opifer\RulesEngineBundle\Provider\Pool
    opifer.rulesengine.twig.rulesengine_extension.class: Opifer\RulesEngineBundle\Twig\RulesEngineExtension


services:

    # Form types

    opifer.rulesengine.form.rulesengine_type:
        class: %opifer.rulesengine.form.rulesengine_type.class%
        tags:
            - { name: form.type, alias: rulesengine }

    opifer.rulesengine.form.condition_type:
        class: %opifer.rulesengine.form.condition_type.class%
        arguments: [@opifer.rulesengine.provider.pool]
        tags:
            - { name: form.type, alias: condition }

    # Providers

    opifer.rulesengine.provider.pool:
        class: %opifer.rulesengine.provider.pool.class%

    opifer.rulesengine.doctrine_provider:
        class: %opifer.rulesengine.doctrine_provider.class%
        arguments: [@doctrine.orm.entity_manager, @request_stack]
        tags:
            - { name: opifer.rulesengine.provider, alias: user }
        calls:
            - [setObject, ["AppBundle\Entity\User"]]

    # Twig Extension

    opifer.rulesengine.twig.rulesengine_extension:
        class: %opifer.rulesengine.twig.rulesengine_extension.class%
        arguments: [@opifer.rulesengine.provider.pool]
        tags:
            - { name: twig.extension }
